export const strings = {
  inr: "INR",
  usd: "USD",
  login: "Login",
  signup: "Sign Up",
  signupSuccess: "Sign Up Successful. Welcome",
  signinSuccess: "Sign in Successful. Welcome",
  fillAllFields: "Please fill all the Fields",
  enterEmail: "Enter email",
  enterPass: "Enter password",
  confirmPass: "Confirm Password",
  logoutSuccess: "Logout Successful!",
  removeFromWatchlist: "Removed from the Watchlist",
  addedToWatchlist: "Added to watchlist",
  currentPrice: "Current Price:",
  searchForCryto: "Search For a Crypto Currency..",
  symbol: "Symbol",
  name: "Name",
  priceInUsd: "Price (USD)",
  hourChange: "24h Change",
  marketcap: "Market Cap",
  favStatus: "Favorite Status",
  errorFetchCoins: "Error fetching coins",
  noItems: "No items in watchlist",
};
